<a href="https://colab.research.google.com/github/PauloSanchez/Data_science_UL/blob/main/Cambio_de_nombre%2C_borrado_y_NaN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![image.png]()

In [32]:
import pandas as pd
df=pd.read_excel('/content/drive/MyDrive/Colab Notebooks/RailsToTrails_National_Count_Data_week.xlsx')
df

,Timeframe,Week of,2019 counts (31 counters),2020 counts (31 counters),2021 Counts,Change 2019-2020,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Week 1,2020-12-30,167679.0,183546.0,NaN,0.094627,1.094627,NaN,NaN,NaN
1,Week 2,2020-01-06,82340.0,97140.0,NaN,0.179743,117.974253,NaN,NaN,NaN
2,Week 3,2020-01-13,62315.0,75782.0,NaN,0.216112,121.611169,NaN,NaN,NaN
3,Week 4,2020-01-20,75801.0,83809.0,NaN,0.105645,110.564504,NaN,NaN,NaN
4,Week 5,2020-01-27,75841.0,94738.0,NaN,0.249166,124.916602,NaN,NaN,NaN
5,Week 6,2020-02-03,79780.0,153555.0,NaN,0.924731,192.473051,NaN,NaN,NaN
6,Week 7,2020-02-10,65732.0,130351.0,NaN,0.983068,198.306761,NaN,NaN,NaN
7,Week 8,2020-02-17,69492.0,149876.0,NaN,1.156737,215.673747,NaN,NaN,NaN
8,Week 9,2020-02-24,85688.0,141250.0,NaN,0.648422,164.842218,NaN,NaN,NaN
9,Week 10,2020-03-02,84512.0,167528.0,NaN,0.982298,198.229837,NaN,NaN,NaN
10,Week 11,2020-03-09,107995.0,210182.0,NaN,0.946220,194.621973,NaN,NaN,NaN
11,Week 12,2020-03-16,125440.0,367795.0,NaN,1.932039,293.203922,NaN,NaN,NaN
12,Week 13,2020-03-23,136330.0,372783.0,NaN,1.730000,273.441649,NaN,NaN,NaN
13,Week 14,2020-03-30,118784.0,280728.0,NaN,1.360000,236.334860,NaN,NaN,NaN
14,Week 15,2020-04-06,132033.0,419160.0,NaN,2.170000,317.466088,NaN,NaN,NaN
15,Week 16,2020-04-13,133267.0,241810.0,NaN,0.810000,181.447770,NaN,NaN,NaN
16,Week 17,2020-04-20,165777.0,231184.0,NaN,0.390000,139.454810,NaN,NaN,NaN
17,Week 18,2020-04-27,166356.0,276982.0,NaN,0.660000,166.499555,NaN,NaN,NaN
18,Week 19,2020-05-04,171049.0,244058.0,NaN,0.430000,142.683091,NaN,NaN,NaN
19,Week 20,2020-05-11,178534.0,281348.0,NaN,0.580000,157.587910,NaN,NaN,NaN
20,Week 21,2020-05-18,191319.0,255226.0,NaN,0.330000,133.403373,NaN,NaN,NaN
21,Week 22,2020-05-25,240507.0,299567.0,NaN,0.250000,124.556458,NaN,NaN,NaN
22,Week 23,2020-06-01,211380.0,278800.0,NaN,0.320000,131.895165,NaN,NaN,NaN
23,Week 24,2020-06-08,214729.0,296335.0,NaN,0.380000,138.004182,NaN,NaN,NaN
24,Week 25,2020-06-15,202847.0,255112.0,NaN,0.260000,125.765725,NaN,NaN,NaN
25,Week 26,2020-06-22,202445.0,256615.0,NaN,0.270000,126.757885,NaN,NaN,NaN
26,Week 27,2020-06-29,184658.0,236287.0,NaN,0.280000,127.959254,NaN,NaN,NaN
27,Week 28,2020-07-06,185302.0,244342.0,NaN,0.320000,131.861502,NaN,NaN,NaN
28,Week 29,2020-07-13,166125.0,250590.0,NaN,0.510000,150.844244,NaN,NaN,NaN
29,Week 30,2020-07-20,208809.0,223757.0,NaN,0.070000,107.158695,NaN,NaN,NaN
30,Week 31,2020-07-27,197005.0,238673.0,NaN,0.210000,121.150732,NaN,NaN,NaN
31,Week 32,2020-08-03,180605.0,239827.0,NaN,0.330000,132.790897,NaN,NaN,NaN
32,Week 33,2020-08-10,191450.0,219279.0,NaN,0.150000,114.535910,NaN,NaN,NaN
33,Week 34,2020-08-17,168754.0,241007.0,NaN,0.430000,142.815578,NaN,NaN,NaN
34,Week 35,2020-08-24,176624.0,273677.0,NaN,0.550000,154.948931,NaN,NaN,NaN
35,Week 36,2020-08-31,184806.0,227918.0,NaN,0.230000,123.328247,NaN,NaN,NaN
36,Week 37,2020-09-07,157345.0,207670.0,NaN,0.320000,131.983857,NaN,NaN,NaN
37,Week 38,2020-09-14,152527.0,207320.0,NaN,0.360000,135.923476,NaN,NaN,NaN
38,Week 39,2020-09-21,141072.0,207918.0,NaN,0.470000,147.384314,NaN,NaN,NaN
39,Week 40,2020-09-28,135881.0,186004.0,NaN,0.370000,136.887424,NaN,NaN,NaN
40,Week 41,2020-10-05,132239.0,182924.0,NaN,0.380000,138.328330,NaN,NaN,NaN
41,Week 42,2020-10-12,110816.0,159246.0,NaN,0.440000,143.703075,NaN,NaN,NaN
42,Week 43,2020-10-19,110761.0,141404.0,NaN,0.280000,127.665875,NaN,NaN,NaN
43,Week 44,2020-10-26,109795.0,147907.0,NaN,0.350000,134.711963,NaN,NaN,NaN
44,Week 45,2020-11-02,109766.0,154502.0,NaN,0.410000,140.755790,NaN,NaN,NaN
45,Week 46,2020-11-09,86824.0,155805.0,NaN,0.790000,179.449231,NaN,NaN,NaN
46,Week 47,2020-11-16,88122.0,97835.0,NaN,0.110000,111.022219,NaN,NaN,NaN
47,Week 48,2020-11-23,72380.0,101036.0,NaN,0.400000,139.591047,NaN,NaN,NaN
48,Week 49,2020-11-30,81871.0,84123.0,NaN,0.030000,102.750669,NaN,NaN,NaN
49,Week 50,2020-12-07,68364.0,92126.0,NaN,0.350000,134.758060,NaN,NaN,NaN
50,Week 51,2020-12-14,58063.0,73188.0,NaN,0.260000,126.049291,NaN,NaN,NaN
51,Week 52,2020-12-21,71890.0,69962.0,NaN,-0.030000,97.318125,NaN,26.728808,0.514016

In [33]:
#1-Se eliminan las columnas indicadas.
df=df.drop(columns=['Unnamed: 7','Unnamed: 8','Unnamed: 9'])
df.head()

,Timeframe,Week of,2019 counts (31 counters),2020 counts (31 counters),2021 Counts,Change 2019-2020,Unnamed: 6
0,Week 1,2020-12-30,167679.0,183546.0,NaN,0.094627,1.094627
1,Week 2,2020-01-06,82340.0,97140.0,NaN,0.179743,117.974253
2,Week 3,2020-01-13,62315.0,75782.0,NaN,0.216112,121.611169
3,Week 4,2020-01-20,75801.0,83809.0,NaN,0.105645,110.564504
4,Week 5,2020-01-27,75841.0,94738.0,NaN,0.249166,124.916602

In [34]:
#2- Se cambia el nombre de la columna.
df.columns=['Timeframe','Week of','2019 counts (31 counters)','2020 counts (31 counters)','2021 Counts','Change 2019-2020','Percent_change']
df.head()

,Timeframe,Week of,2019 counts (31 counters),2020 counts (31 counters),2021 Counts,Change 2019-2020,Percent_change
0,Week 1,2020-12-30,167679.0,183546.0,NaN,0.094627,1.094627
1,Week 2,2020-01-06,82340.0,97140.0,NaN,0.179743,117.974253
2,Week 3,2020-01-13,62315.0,75782.0,NaN,0.216112,121.611169
3,Week 4,2020-01-20,75801.0,83809.0,NaN,0.105645,110.564504
4,Week 5,2020-01-27,75841.0,94738.0,NaN,0.249166,124.916602

In [35]:
#3-Conteo de nulos e identificación de columna.
NaN=df.isnull().sum(axis=0) # Cuenta los datos NaN en la columna.
NaN

Timeframe                     0
Week of                       0
2019 counts (31 counters)     0
2020 counts (31 counters)     0
2021 Counts                  52
Change 2019-2020              0
Percent_change                0
dtype: int64

In [40]:
#4- Se reemplazan los nulos o faltantes de la columna por un cero
df=df.fillna(0)
df.head()

,Timeframe,Week of,2019 counts (31 counters),2020 counts (31 counters),2021 Counts,Change 2019-2020,Percent_change
0,Week 1,2020-12-30,167679.0,183546.0,0.0,0.094627,1.094627
1,Week 2,2020-01-06,82340.0,97140.0,0.0,0.179743,117.974253
2,Week 3,2020-01-13,62315.0,75782.0,0.0,0.216112,121.611169
3,Week 4,2020-01-20,75801.0,83809.0,0.0,0.105645,110.564504
4,Week 5,2020-01-27,75841.0,94738.0,0.0,0.249166,124.916602