<a href="https://colab.research.google.com/github/PauloSanchez/Data_science_UL/blob/main/Proyecto_2_parte_2_Paulo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Importamos lubreria pandas para carga de datos.
import pandas as pd

df = pd.read_excel('/content/drive/MyDrive/Colab Notebooks/Archivos ejercicios/Proyecto 2/Historico_DCIW_Resueltos.xlsx')
df.head()

,Número de documento,CC,Planta,Tipo,ID de escaneo,Fecha de escaneo,Fecha de Vencimiento,Fecha Doc.,Asignado a,Acción,...,Concepto,Conca,Generación,Motivo general,Sub-Motivo,Monto al P&L (CLP),Fecha Resolución,Mes,Año,Semana
0,155109.0,2247.0,0.0,INVPO,20210519_LXT8TSD360,05/19/2021,08/16/2021,05/18/2021,VANIA.BLANCO,Esperando la acción del Aprobador de GR (R400),...,HONORARIO AGENCIA,15510950535712.0,Caso Antiguo,No Planificado,No provisionado,31647.058824,2022-06-23,Junio,2022.0,25.0
1,155109.0,2247.0,0.0,INVPO,20210519_LXT8TSD360,05/19/2021,08/16/2021,05/18/2021,XIMENA.TEJO,Waiting GR Approver Action (R400),...,HONORARIO AGENCIA,15510950535712.0,Caso Devuelto,No Planificado,Cambio de PO (DE-PARA),31647.058824,2022-09-06,Septiembre,2022.0,36.0
2,82918.0,2247.0,0.0,INVPO,20210709_LSE6GAY973,07/09/2021,08/15/2021,05/17/2021,EQUIPO IBM,Waiting GR Approver Action (R400),...,HONORARIO AGENCIA,8291850535712.0,Caso Antiguo,No Planificado,KTOP,760479.831933,2022-09-09,Septiembre,2022.0,36.0
3,224496.0,2247.0,0.0,INVPO,20210727_LS9OB34430,07/27/2021,05/16/2021,05/16/2021,XIMENA.TEJO,Esperando la acción del Aprobador de GR (R400),...,"CONEXION, DESCONEXION CONT.REFRIG.",22449610123316.0,Caso Antiguo,Planificado con diferencia,Sub-provisión,0.000000,2022-09-01,Septiembre,2022.0,35.0
4,162544.0,2247.0,0.0,INVPO,20210927_LXEQO1Z858,09/27/2021,12/23/2021,09/24/2021,VANIA.BLANCO,Waiting GR Approver Action (R400),...,HONORARIO AGENCIA,16254450535712.0,Caso Antiguo,No Planificado,KTOP,108952.100840,2022-07-15,Julio,2022.0,28.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8058 entries, 0 to 8057
Data columns (total 42 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Número de documento         8058 non-null   object
 1   CC                          8058 non-null   float64
 2   Planta                      8058 non-null   float64
 3   Tipo                        8058 non-null   object
 4   ID de escaneo               8058 non-null   object
 5   Fecha de escaneo            8058 non-null   object
 6   Fecha de Vencimiento        7563 non-null   object
 7   Fecha Doc.                  7563 non-null   object
 8   Asignado a                  8058 non-null   object
 9   Acción                      7563 non-null   object
 10  Razón                       8058 non-null   object
 11  Fecha de estado             7563 non-null   object
 12  Monto Total                 8058 non-null   float64
 13  Moneda                      8058 non-null   object
 14  Número de OC                7952 non-null   object
 15  No. del proveedor           8058 non-null   object
 16  Nombre del proveedor        8058 non-null   object
 17  RFC del proveedor           477 non-null    object
 18  Fecha escaneo               7563 non-null   object
 19  Fecha Documento             7563 non-null   object
 20  Numero de PO                6252 non-null   object
 21  Categoria                   2486 non-null   object
 22  PO TEXTO                    2485 non-null   object
 23  Cant. Digito PO (10)        8058 non-null   float64
 24  Monto total Neto            8055 non-null   float64
 25  Monto PO/Vendor DCIW        8058 non-null   float64
 26  Monto PO/Vendor MB5S        8058 non-null   object
 27  Diferencias (TH 100 Euros)  8058 non-null   float64
 28  Status                      8057 non-null   object
 29  Área Responsable            8058 non-null   object
 30  Año Documento               8058 non-null   float64
 31  Rango antigüedad            7563 non-null   object
 32  Concepto                    8058 non-null   object
 33  Conca                       8058 non-null   object
 34  Generación                  7563 non-null   object
 35  Motivo general              8058 non-null   object
 36  Sub-Motivo                  8057 non-null   object
 37  Monto al P&L (CLP)          8055 non-null   float64
 38  Fecha Resolución            8058 non-null   datetime64[ns]
 39  Mes                         8058 non-null   object
 40  Año                         8058 non-null   float64
 41  Semana                      8058 non-null   float64
dtypes: datetime64[ns](1), float64(11), object(30)
memory usage: 2.6+ MB

Se observan valores nulos o vacios en el dataframe, lñas columnas que no agregan valor al modelo se eliminarán y dejaremos solo aquellos que le sirven.

In [ ]:
df = df.drop(columns=['RFC del proveedor','CC','Planta','Acción','Conca','Cant. Digito PO (10)','Área Responsable','Diferencias (TH 100 Euros)',
                      'Monto PO/Vendor MB5S','Monto PO/Vendor DCIW','Número de OC','PO TEXTO','Fecha de Vencimiento','Categoria','Numero de PO',
                      'Fecha de estado','Fecha Doc.','Fecha Documento','Fecha escaneo','Rango antigüedad','Generación'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8058 entries, 0 to 8057
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Número de documento   8058 non-null   object
 1   Tipo                  8058 non-null   object
 2   ID de escaneo         8058 non-null   object
 3   Fecha de escaneo      8058 non-null   object
 4   Asignado a            8058 non-null   object
 5   Razón                 8058 non-null   object
 6   Monto Total           8058 non-null   float64
 7   Moneda                8058 non-null   object
 8   No. del proveedor     8058 non-null   object
 9   Nombre del proveedor  8058 non-null   object
 10  Monto total Neto      8055 non-null   float64
 11  Status                8057 non-null   object
 12  Año Documento         8058 non-null   float64
 13  Concepto              8058 non-null   object
 14  Motivo general        8058 non-null   object
 15  Sub-Motivo            8057 non-null   object
 16  Monto al P&L (CLP)    8055 non-null   float64
 17  Fecha Resolución      8058 non-null   datetime64[ns]
 18  Mes                   8058 non-null   object
 19  Año                   8058 non-null   float64
 20  Semana                8058 non-null   float64
dtypes: datetime64[ns](1), float64(6), object(14)
memory usage: 1.3+ MB

Para el caso de la columna "Monto al P&L (CLP)" se rellenaran con cero los nulos, pues es altamente probable que ese sea el caso, de "Status" se reemplazarán por "Merge" y "Sub-motivo" se eliminarán las filas, pues es complejo entender a que sub-motivo corresponde.

In [ ]:
df['Status'] = df['Status'].fillna("Merge")
df['Monto al P&L (CLP)'] = df['Monto al P&L (CLP)'].fillna("0")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8058 entries, 0 to 8057
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Número de documento   8058 non-null   object
 1   Tipo                  8058 non-null   object
 2   ID de escaneo         8058 non-null   object
 3   Fecha de escaneo      8058 non-null   object
 4   Asignado a            8058 non-null   object
 5   Razón                 8058 non-null   object
 6   Monto Total           8058 non-null   float64
 7   Moneda                8058 non-null   object
 8   No. del proveedor     8058 non-null   object
 9   Nombre del proveedor  8058 non-null   object
 10  Monto total Neto      8055 non-null   float64
 11  Status                8058 non-null   object
 12  Año Documento         8058 non-null   float64
 13  Concepto              8058 non-null   object
 14  Motivo general        8058 non-null   object
 15  Sub-Motivo            8057 non-null   object
 16  Monto al P&L (CLP)    8058 non-null   object
 17  Fecha Resolución      8058 non-null   datetime64[ns]
 18  Mes                   8058 non-null   object
 19  Año                   8058 non-null   float64
 20  Semana                8058 non-null   float64
dtypes: datetime64[ns](1), float64(5), object(15)
memory usage: 1.3+ MB

Los NAN que van quedando se eliminarán considerando que son máx 4 filas.

In [ ]:
df = df.dropna()
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8054 entries, 0 to 8057
Data columns (total 21 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Número de documento   8054 non-null   object
 1   Tipo                  8054 non-null   object
 2   ID de escaneo         8054 non-null   object
 3   Fecha de escaneo      8054 non-null   object
 4   Asignado a            8054 non-null   object
 5   Razón                 8054 non-null   object
 6   Monto Total           8054 non-null   float64
 7   Moneda                8054 non-null   object
 8   No. del proveedor     8054 non-null   object
 9   Nombre del proveedor  8054 non-null   object
 10  Monto total Neto      8054 non-null   float64
 11  Status                8054 non-null   object
 12  Año Documento         8054 non-null   float64
 13  Concepto              8054 non-null   object
 14  Motivo general        8054 non-null   object
 15  Sub-Motivo            8054 non-null   object
 16  Monto al P&L (CLP)    8054 non-null   object
 17  Fecha Resolución      8054 non-null   datetime64[ns]
 18  Mes                   8054 non-null   object
 19  Año                   8054 non-null   float64
 20  Semana                8054 non-null   float64
dtypes: datetime64[ns](1), float64(5), object(15)
memory usage: 1.4+ MB